<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #222; font-size: 10px; }
        h1 { font-size: 17px; margin: 0 0 4px; }
        h2 { font-size: 14px; margin: 18px 0 8px; }
        .meta { line-height: 1.6; margin-bottom: 16px; }
        .notice { color: #666; font-size: 9px; margin-bottom: 12px; }
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #bbb; padding: 5px 4px; vertical-align: top; }
        th { background: #eee; }
        .number { text-align: right; white-space: nowrap; }
    </style>
</head>
<body>
<h1>{{ $customer->branch?->name ?: 'Oreoluwapo CT&CU' }}</h1>
<div>{{ $customer->branch?->address }}</div>
<h2>Member Portal Statement</h2>
<div class="meta">
    <strong>Member:</strong> {{ $customer->name }}<br>
    <strong>Member number:</strong> {{ $customer->display_member_no ?: 'N/A' }}<br>
    <strong>Period:</strong> {{ !empty($filters['start_date']) ? \Carbon\Carbon::parse($filters['start_date'])->format('d M Y') : 'First transaction' }}
    to {{ !empty($filters['end_date']) ? \Carbon\Carbon::parse($filters['end_date'])->format('d M Y') : 'Present' }}<br>
    <strong>Generated:</strong> {{ now()->format('d M Y, h:i A') }}
</div>
<div class="notice">Generated by the member through the Member Portal.</div>
<table>
    <thead><tr><th>Date</th><th>Account</th><th>Particulars</th><th>Method</th><th>Type</th><th class="number">Amount (₦)</th></tr></thead>
    <tbody>
    @forelse ($transactions as $transaction)
        <tr>
            <td>{{ $transaction->trans_date?->format('d M Y') ?: 'N/A' }}</td>
            <td>{{ $transaction->account?->account_number ?: 'Loan ledger' }}<br>{{ $transaction->account?->product?->type ?: ($transaction->type ?: 'Other') }}</td>
            <td>{{ $transaction->description ?: ($transaction->note ?: 'Transaction') }}</td>
            <td>{{ $transaction->method ?: 'N/A' }}</td>
            <td>{{ app(\App\Services\MemberStatementService::class)->memberDirection($transaction) }}</td>
            <td class="number">{{ number_format((float) $transaction->amount, 2) }}</td>
        </tr>
    @empty
        <tr><td colspan="6">No transactions match the selected filters.</td></tr>
    @endforelse
    </tbody>
</table>
</body>
</html>
